import { useEffect, useMemo, useState } from "react";
import {
  api,
  adminApi,
  Transaction,
  TxFilter,
  TransactionsPage,
} from "../api";
import { useResource } from "../lib/useApi";
import { EmptyState, Skeleton } from "./ui";

const TYPE_FA: Record<string, string> = {
  topup: "شارژ",
  usage_debit: "مصرف",
  usage_credit: "درآمد",
  commission: "کارمزد",
  refund: "بازگشت",
  payout: "برداشت",
  adjustment: "تنظیم دستی",
};

const TYPE_OPTIONS: { value: string; label: string }[] = [
  { value: "topup", label: TYPE_FA.topup },
  { value: "usage_debit", label: TYPE_FA.usage_debit },
  { value: "usage_credit", label: TYPE_FA.usage_credit },
  { value: "refund", label: TYPE_FA.refund },
  { value: "payout", label: TYPE_FA.payout },
  { value: "adjustment", label: TYPE_FA.adjustment },
];

function formatAmount(raw: string): { sign: "+" | "-" | ""; abs: string } {
  const n = parseFloat(raw);
  if (!Number.isFinite(n)) return { sign: "", abs: raw };
  const sign: "+" | "-" | "" = n > 0 ? "+" : n < 0 ? "-" : "";
  return {
    sign,
    abs: Math.abs(n).toLocaleString("en-US", {
      minimumFractionDigits: 0,
      maximumFractionDigits: 4,
    }),
  };
}

function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return "۰ بایت";
  const units = ["بایت", "کیلوبایت", "مگابایت", "گیگابایت", "ترابایت"];
  let i = 0;
  let v = bytes;
  while (v >= 1024 && i < units.length - 1) {
    v /= 1024;
    i += 1;
  }
  const num = v.toLocaleString("fa-IR", {
    minimumFractionDigits: 0,
    maximumFractionDigits: v < 10 ? 2 : v < 100 ? 1 : 0,
  });
  return `${num} ${units[i]}`;
}

function formatPriceFa(usd: string): string {
  const n = parseFloat(usd);
  if (!Number.isFinite(n)) return usd;
  return n.toLocaleString("fa-IR", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 4,
  });
}

function formatPctFa(frac: string): string {
  const n = parseFloat(frac);
  if (!Number.isFinite(n)) return frac;
  return Math.round(n * 100).toLocaleString("fa-IR");
}

function formatRelative(iso: string): string {
  try {
    const d = new Date(iso);
    const now = new Date();
    const sameDay =
      d.getFullYear() === now.getFullYear() &&
      d.getMonth() === now.getMonth() &&
      d.getDate() === now.getDate();
    const yesterday = new Date(now);
    yesterday.setDate(now.getDate() - 1);
    const isYesterday =
      d.getFullYear() === yesterday.getFullYear() &&
      d.getMonth() === yesterday.getMonth() &&
      d.getDate() === yesterday.getDate();
    const time = d.toLocaleTimeString("fa-IR", {
      hour: "2-digit",
      minute: "2-digit",
    });
    if (sameDay) return `امروز، ${time}`;
    if (isYesterday) return `دیروز، ${time}`;
    const diffDays = Math.floor(
      (now.getTime() - d.getTime()) / (1000 * 60 * 60 * 24),
    );
    if (diffDays > 0 && diffDays < 7) {
      return `${diffDays.toLocaleString("fa-IR")} روز پیش، ${time}`;
    }
    return d.toLocaleDateString("fa-IR", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return iso;
  }
}

function formatDayHeader(iso: string): string {
  try {
    const d = new Date(iso);
    const now = new Date();
    const sameDay =
      d.getFullYear() === now.getFullYear() &&
      d.getMonth() === now.getMonth() &&
      d.getDate() === now.getDate();
    if (sameDay) return "امروز";
    const yesterday = new Date(now);
    yesterday.setDate(now.getDate() - 1);
    const isYesterday =
      d.getFullYear() === yesterday.getFullYear() &&
      d.getMonth() === yesterday.getMonth() &&
      d.getDate() === yesterday.getDate();
    if (isYesterday) return "دیروز";
    return d.toLocaleDateString("fa-IR", {
      weekday: "long",
      day: "numeric",
      month: "long",
    });
  } catch {
    return iso;
  }
}

function dayKey(iso: string): string {
  try {
    const d = new Date(iso);
    return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
  } catch {
    return iso;
  }
}

const TYPE_ICON: Record<string, string> = {
  topup: "+",
  usage_debit: "↓",
  usage_credit: "↑",
  commission: "٪",
  refund: "↺",
  payout: "↗",
  adjustment: "✎",
};

function describeTx(t: Transaction): string | null {
  // Parse the developer-style notes generated by poll_traffic.py and
  // turn them into a natural Persian sentence. Falls back to the raw
  // note (or null) for other transaction types.
  if (t.note) {
    if (t.type === "usage_credit") {
      const m = t.note.match(/outbound\s+(\d+)B\s*@\s*([\d.]+)\/GB/i);
      if (m) {
        const bytes = parseInt(m[1], 10);
        return `${formatBytes(bytes)} مصرف اوت‌باند با نرخ $${formatPriceFa(m[2])} به ازای هر گیگ`;
      }
    }
    if (t.type === "usage_debit") {
      const m = t.note.match(
        /usage\s+(\d+)B\s*@\s*([\d.]+)\/GB/i,
      );
      if (m) {
        const bytes = parseInt(m[1], 10);
        return `${formatBytes(bytes)} مصرف کانفیگ با نرخ $${formatPriceFa(m[2])} به ازای هر گیگ`;
      }
    }
    return t.note;
  }
  return null;
}

function txTone(
  t: Transaction,
): "credit" | "debit" | "topup" | "payout" | "adjustment" | "commission" {
  switch (t.type) {
    case "topup":
      return "topup";
    case "payout":
      return "payout";
    case "commission":
      return "commission";
    case "adjustment":
      return "adjustment";
    case "usage_credit":
    case "refund":
      return "credit";
    case "usage_debit":
    default:
      return "debit";
  }
}

function TxRow({ t, showRef }: { t: Transaction; showRef: boolean }) {
  const { sign, abs } = formatAmount(t.amount);
  const tone = txTone(t);
  const amountClass =
    sign === "+" ? "tx-amount-pos" : sign === "-" ? "tx-amount-neg" : "";
  const description = describeTx(t);
  return (
    <div className={`tx-card tx-tone-${tone}`}>
      <div className={`tx-icon tx-icon-${tone}`} aria-hidden="true">
        {TYPE_ICON[t.type] ?? "•"}
      </div>
      <div className="tx-body">
        <div className="tx-head">
          <span className="tx-title">{TYPE_FA[t.type] ?? t.type}</span>
          <span className="tx-time">{formatRelative(t.created_at)}</span>
        </div>
        {description && <div className="tx-desc">{description}</div>}
        {showRef && t.ref && (
          <div className="tx-ref" dir="ltr">
            <code>{t.ref}</code>
          </div>
        )}
      </div>
      <div className={`tx-amount ${amountClass}`} dir="ltr">
        <span className="tx-amount-value">
          {sign}
          {abs}
        </span>
        <span className="tx-amount-unit">{t.currency}</span>
      </div>
    </div>
  );
}

export type TransactionsListProps = {
  /** If set, fetches via admin endpoint for that user instead of /api/me. */
  adminUserId?: number;
};

export function TransactionsList({ adminUserId }: TransactionsListProps) {
  const [selectedTypes, setSelectedTypes] = useState<Set<string>>(new Set());
  const [direction, setDirection] = useState<"all" | "credit" | "debit">("all");
  const [from, setFrom] = useState<string>("");
  const [to, setTo] = useState<string>("");
  const [page, setPage] = useState<number>(1);
  const size = 20;

  const filter: TxFilter = useMemo(() => {
    const typeCsv = Array.from(selectedTypes).join(",");
    const f: TxFilter = { page, size };
    if (typeCsv) f.type = typeCsv;
    if (direction !== "all") f.direction = direction;
    if (from) f.from = new Date(from).toISOString();
    if (to) {
      // include the whole "to" day
      const d = new Date(to);
      d.setHours(23, 59, 59, 999);
      f.to = d.toISOString();
    }
    return f;
  }, [selectedTypes, direction, from, to, page]);

  const fetcher = () =>
    adminUserId !== undefined
      ? adminApi.listUserTransactions(adminUserId, filter)
      : api.listMyTransactions(filter);

  const { data, loading, error, refetch } = useResource<TransactionsPage>(
    fetcher,
    [adminUserId, JSON.stringify(filter)],
  );

  // Auto-refetch when the WebApp becomes visible again (e.g. user reopens
  // the mini-app after an admin posts a manual transaction in the bot).
  useEffect(() => {
    function onVisible() {
      if (document.visibilityState === "visible") {
        refetch();
      }
    }
    document.addEventListener("visibilitychange", onVisible);
    return () => document.removeEventListener("visibilitychange", onVisible);
  }, [refetch]);

  function toggleType(v: string) {
    setSelectedTypes((cur) => {
      const next = new Set(cur);
      if (next.has(v)) next.delete(v);
      else next.add(v);
      return next;
    });
    setPage(1);
  }

  function reset() {
    setSelectedTypes(new Set());
    setDirection("all");
    setFrom("");
    setTo("");
    setPage(1);
  }

  const totalPages = data ? Math.max(1, Math.ceil(data.total / size)) : 1;

  return (
    <div>
      <div className="card">
        <div className="title" style={{ fontSize: 14, marginBottom: 8 }}>
          فیلترها
        </div>
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 6,
            marginBottom: 8,
          }}
        >
          {TYPE_OPTIONS.map((opt) => {
            const active = selectedTypes.has(opt.value);
            return (
              <button
                key={opt.value}
                type="button"
                className={"badge" + (active ? " badge-active" : "")}
                onClick={() => toggleType(opt.value)}
                style={{
                  border: active
                    ? "1px solid var(--accent, #2a73ff)"
                    : "1px solid var(--border, #ddd)",
                  background: active
                    ? "var(--accent, #2a73ff)"
                    : "transparent",
                  color: active ? "#fff" : "inherit",
                  cursor: "pointer",
                }}
              >
                {opt.label}
              </button>
            );
          })}
        </div>
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 8,
            alignItems: "center",
          }}
        >
          <label style={{ fontSize: 12 }}>
            جهت:&nbsp;
            <select
              value={direction}
              onChange={(e) => {
                setDirection(e.target.value as "all" | "credit" | "debit");
                setPage(1);
              }}
            >
              <option value="all">همه</option>
              <option value="credit">واریز</option>
              <option value="debit">برداشت</option>
            </select>
          </label>
          <label style={{ fontSize: 12 }}>
            از:&nbsp;
            <input
              type="date"
              value={from}
              onChange={(e) => {
                setFrom(e.target.value);
                setPage(1);
              }}
            />
          </label>
          <label style={{ fontSize: 12 }}>
            تا:&nbsp;
            <input
              type="date"
              value={to}
              onChange={(e) => {
                setTo(e.target.value);
                setPage(1);
              }}
            />
          </label>
          <button className="btn-ghost" type="button" onClick={reset}>
            ریست
          </button>
          <button
            className="btn-ghost"
            type="button"
            onClick={() => refetch()}
            disabled={loading}
          >
            بروزرسانی
          </button>
        </div>
      </div>

      {error && (
        <div className="alert alert-error">
          {error}{" "}
          <button
            className="btn-ghost"
            type="button"
            onClick={refetch}
            style={{
              background: "none",
              border: "none",
              padding: 0,
              color: "inherit",
              textDecoration: "underline",
            }}
          >
            تلاش مجدد
          </button>
        </div>
      )}

      {loading && !data && (
        <div className="card">
          <Skeleton width="40%" height={14} />
          <div style={{ height: 8 }} />
          <Skeleton width="80%" height={12} />
        </div>
      )}

      {data && data.items.length === 0 && (
        <EmptyState emoji="🧾" title="تراکنشی یافت نشد" />
      )}

      {data &&
        data.items.length > 0 &&
        data.items.map((t, idx) => {
          const prev = idx > 0 ? data.items[idx - 1] : null;
          const showHeader =
            !prev || dayKey(prev.created_at) !== dayKey(t.created_at);
          return (
            <div key={t.id}>
              {showHeader && (
                <div className="tx-day-header">
                  {formatDayHeader(t.created_at)}
                </div>
              )}
              <TxRow t={t} showRef={adminUserId !== undefined} />
            </div>
          );
        })}

      {data && data.total > size && (
        <div
          className="row"
          style={{ justifyContent: "center", gap: 12, marginTop: 8 }}
        >
          <button
            type="button"
            className="btn-ghost"
            disabled={page <= 1}
            onClick={() => setPage((p) => Math.max(1, p - 1))}
          >
            قبلی
          </button>
          <span className="muted" style={{ fontSize: 12 }}>
            {page} از {totalPages}
          </span>
          <button
            type="button"
            className="btn-ghost"
            disabled={page >= totalPages}
            onClick={() => setPage((p) => p + 1)}
          >
            بعدی
          </button>
        </div>
      )}
    </div>
  );
}
